# Generated by Django 5.0.7 on 2024-07-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_books_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categories', models.CharField(max_length=200)),
                ('cover_url', models.URLField()),
            ],
        ),
    ]
